name: test

on: push

jobs:
  job:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    
    steps:
      - name: python command
        run: python -c "import platform; print(platform.system())
